CREATE TABLE user_table(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(15) NOT NULL,
last_name VARCHAR(15) NOT NULL,
email VARCHAR(20) NOT NULL UNIQUE,
login VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(20) NOT NULL,
role ENUM("Admin", "librarian", "Reader") NOT NULL
);

CREATE TABLE book(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
quantity INT DEFAULT 1);

CREATE TABLE order_book(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
book_id INTEGER NOT NULL,
user_id INTEGER NOT NULL,
order_date DATE NOT NULL,
returning_date DATE NOT NULL,
reading_place ENUM("Hall", "Home") NOT NULL,
book_returned BOOLEAN DEFAULT 0,
FOREIGN KEY(book_id) REFERENCES book(id),
FOREIGN KEY(user_id) REFERENCES user_table(id)
)