insert into book_table (book_title, quantity) values ('Downy Goldenrod', 84);
insert into book_table (book_title, quantity) values ('Southwestern Pricklypoppy', 17);
insert into book_table (book_title, quantity) values ('Lanceleaf Sage', 57);
insert into book_table (book_title, quantity) values ('Spinystar', 80);
insert into book_table (book_title, quantity) values ('Camwood', 31);
insert into book_table (book_title, quantity) values ('Alpine False Candytuft', 98);
insert into book_table (book_title, quantity) values ('Guaje', 92);
insert into book_table (book_title, quantity) values ('Farinose Crabseye Lichen', 52);
insert into book_table (book_title, quantity) values ('Hasse''s Cracked Lichen', 26);
insert into book_table (book_title, quantity) values ('Lesser Snapdragon', 13);
insert into book_table (book_title, quantity) values ('Tellicherry Bark', 36);
insert into book_table (book_title, quantity) values ('Gray Rupturewort', 65);
insert into book_table (book_title, quantity) values ('Orange Lichen', 23);
insert into book_table (book_title, quantity) values ('Hybrid Oak', 75);
insert into book_table (book_title, quantity) values ('Gila Rockdaisy', 33);
insert into book_table (book_title, quantity) values ('Mustard', 90);
insert into book_table (book_title, quantity) values ('Chicita''s Giant Shield Lichen', 63);
insert into book_table (book_title, quantity) values ('Canada Spikesedge', 84);
insert into book_table (book_title, quantity) values ('Hepatica', 92);
insert into book_table (book_title, quantity) values ('Orthotrichum Moss', 31);
insert into book_table (book_title, quantity) values ('Yellow Wild Indigo', 38);
insert into book_table (book_title, quantity) values ('Gaymallow', 6);
insert into book_table (book_title, quantity) values ('Helodium Moss', 66);
insert into book_table (book_title, quantity) values ('Shasta Panicgrass', 4);
insert into book_table (book_title, quantity) values ('Disc Lichen', 34);
insert into book_table (book_title, quantity) values ('Creeping Meadow Foxtail', 4);
insert into book_table (book_title, quantity) values ('Myrtleleaf Peperomia', 86);
insert into book_table (book_title, quantity) values ('Sierra Milkwort', 73);
insert into book_table (book_title, quantity) values ('Fivelobe Cucumber', 12);
insert into book_table (book_title, quantity) values ('Tetraphis Moss', 69);
insert into book_table (book_title, quantity) values ('Mediterranean Sweetclover', 75);
insert into book_table (book_title, quantity) values ('Sneezeweed', 36);
insert into book_table (book_title, quantity) values ('Hyophila Moss', 97);
insert into book_table (book_title, quantity) values ('Gooseberryleaf Alumroot', 20);
insert into book_table (book_title, quantity) values ('Fiddleleaf Tobacco', 62);
insert into book_table (book_title, quantity) values ('Ricegrass', 3);
insert into book_table (book_title, quantity) values ('Humboldt''s Lily', 79);
insert into book_table (book_title, quantity) values ('Seaside Threeawn', 37);
insert into book_table (book_title, quantity) values ('Oriental Bittersweet', 12);
insert into book_table (book_title, quantity) values ('Helocarpon Lichen', 92);
insert into book_table (book_title, quantity) values ('Violet', 48);
insert into book_table (book_title, quantity) values ('Parrothead Indian Paintbrush', 63);
insert into book_table (book_title, quantity) values ('Early Sandgrass', 34);
insert into book_table (book_title, quantity) values ('Longleaf Rush', 30);
insert into book_table (book_title, quantity) values ('Miquel''s Mazus', 30);
insert into book_table (book_title, quantity) values ('Rock Goldenrod', 9);
insert into book_table (book_title, quantity) values ('Geyer''s Larkspur', 52);
insert into book_table (book_title, quantity) values ('Leonard''s Skullcap', 57);
insert into book_table (book_title, quantity) values ('Field Goldeneye', 35);
insert into book_table (book_title, quantity) values ('Arctic Rush', 60);
